#!/bin/sh

cd manpages
mkdir -p ../htmlsrc/manpages
OUT=../htmlsrc/manpages/index.html
echo "<ul>" >$OUT
for f in *.html
do
        basename=$(basename $f .html)
        echo "<li> <a href=\"$f\">$basename</a> (<a href=\"$basename.txt\">txt</a>) </li>" >>$OUT
done
echo "</ul>" >>$OUT
#mv $OUT index.html



